package de.seleri.impulse

import android.os.Bundle
import android.widget.Button
import androidx.appcompat.app.AppCompatActivity
import kotlin.random.Random

class Spiel2Activity : AppCompatActivity() {

    @Suppress("MaxLineLength")
    private val von0bis100 = listOf(
        "Wie schüchtern bist du?",
        "Wie gerne würdest du Geheimagent werden wollen?",
        "Wie gerne würdest du auf der ersten Marskolonie leben (für 5 Jahre, einschließlich der Reise)?",
        "Wie gerne kochst du?",
        "Wie wichtig ist dir Familie?",
        "Wie sehr magst du das Land, in dem du aktuell lebst?",
        "Wie gelenkig bist du?",
        "Wie gut ist dein Gedächtnis?",
        "Wie zufrieden bist du bis jetzt mit deinem heutigen Tag?",
        "Wie sehr bist du jemand, der Dinge überstürzt?",
        "Wie gerne gehst du zu Konzerten oder Musikfestivals?",
        "Wie sehr kümmert es dich, was andere Menschen über dich denken?",
        "Wie sehr magst du Musicals?",
        "Wie wichtig ist dir Essen?",
        "Wie gerne liest du, während du auf der Toilette sitzt?",
        "Wie groß ist dein Interesse, an einer Reality-Show im Fernsehen teilzunehmen?",
        "Wie groß ist deine Höhenangst?",
        "Wie groß ist dein Interesse, den Papst persönlich zu treffen?",
        "Wie gerne würdest du einmal Bungee springen?",
        "Wie gerne tanzt du?",
        "Wie faul bist du?",
        "Wie erwachsen fühlst du dich?",
        "Wie gerne feierst du deinen Geburtstag?",
        "Wie sehr magst du deine momentane Frisur?",
        "Wie sehr magst du deinen Vornamen?",
        "Wie schick bist du heute deiner Meinung nach angezogen?",
        "Wie gerne trainierst du deine Fitness?",
        "Wie sehr hast du Angst vor der Dunkelheit?",
        "Wie gut kannst du ohne Rezept kochen?",
        "Wie schlecht kannst du verlieren?",
        "Wie sehr magst du Familienzusammenkünfte?",
        "Wie schnell fühlst du dich beleidigt, angegriffen, verletzt ...?",
        "Wie wichtig sind dir Traditionen?",
        "Wie sehr magst du Umarmungen?",
        "Wie viel Fantasie hast du?",
        "Wie sehr magst du Tiere?",
        "Wie gern würdest du einmal Fallschirmspringen?",
        "Wie sehr bist du jemand, der Dinge kurz vor knapp in letzter Minute erledigt?",
        "Wie sehr magst du Disney-Filme?",
        "Wie gerne erstellst du Listen?",
        "Wie abergläubisch bist du?",
        "Wie groß ist deine Angst vor Spinnen?",
        "Wie gern wärst du Bundeskanzler oder Bundeskanzlerin?",
        "Wie sorgfältig trennst du deinen Müll?",
        "Wie gerne würdest du in einem Hollywood-Film mitspielen?",
        "Wie sehr liegt dir Gartenarbeit?",
        "Wie wohl fühlst du dich, wenn du vor größerem Publikum sprichst?",
        "Wie gut kannst du mit Kindern umgehen?",
        "Wie gerne erzählst du Witze?",
        "Wie gerne bist du unter Menschen?",
        "Wie verführerisch bist du deiner Meinung nach?",
        "Wie sehr beeinflusst das Wetter deine Stimmung?",
        "Wie sehr magst du Comics?",
        "Wie wohl fühlst du dich im allgemeinen Bezug auf Nacktheit?",
        "Wie oft bist du für neue Erfahrungen?",
        "Wie sehr magst du Dokumentarfilme?",
        "Wie gerne sprichst du mit fremden Menschen?",
        "Wie feministisch bist du eingestellt?",
        "Wie sehr magst du Karaoke?",
        "Wie sehr musst du immer das letzte Wort haben?",
        "Du siehst ein niedliches, kleines Kätzchen. Wie entzückt rufst du \"ohhh\"?",
        "Wie viel Angst hast du vor dem Zahnarzt?",
        "Wie gesund ernährst du dich normalerweise?",
        "Wie viel läge dir daran, berühmt zu sein?",
        "Wie sehr bist du bereit, dein Essen mit anderen zu teilen?",
        "Wie sehr magst du Horrorfilme?",
        "Wie gut wärst du darin, eine Zombie-Apokalypse zu überleben?",
        "Wie gerne spielst du Video- oder Computerspiele?",
        "Wie sehr fährst du auf die aktuell neuesten technischen Geräten ab?",
        "Wie wichtig wäre es dir, ein Porträt von dir in einem Museum hängen zu haben?",
        "Wie gerne führst du Telefongespräche?",
        "Wie mürrisch wirst du, wenn du viel zu wenig geschlafen hast?",
        "Wie sehr magst du abstrakte Kunst?",
        "Wie sehr magst du Kostümpartys?",
        "Wie gerne bist du im Wasser?",
        "Wie viel besser war alles deiner Meinung nach früher?",
        "Wie ungeschickt bist du?",
        "Was denkst du, wie mutig du bist?",
        "Wie gerne würdest du in eine Geheimgesellschaft eintreten?",
        "Wie wählerisch bist du beim Essen?",
        "Wie ehrgeizig bist du im Berufsleben?",
        "Wie mürrisch wirst du, wenn du Hunger hast?",
        "Wie gerne würdest du in Hogwarts zur Schule gehen?",
        "Wie gerne gehst du shoppen?",
        "Wie sehr befolgst du geltende Regeln?",
        "Wie kreativ bist du?",
        "Wie gut kannst du mit alten Menschen umgehen?",
        "Wie sehr liegt dir Teamarbeit?",
        "Wie gerne gibst du Partys bei dir zu Hause?",
        "Wie schwer fällt es dir, etwas wegzuwerfen, \"weil man es ja vielleicht noch brauchen kann\"?",
        "Wie sehr macht es dir Spaß, Dinge selbst zu reparieren?",
        "Wie sehr stimmst du mit dem Spruch \"Glück kann man kaufen\" überein?"
    )

    @Suppress("MaxLineLength")
    private val freitextfragen = listOf(
        "Wie viel Eintritt würdest du höchstens für einen Freizeitpark mit echten, lebenden Dinosauriern bezahlen?",
        "Wie viele Zimmer hat dein Zuhause?",
        "Wie viele Freunde hast du auf Facebook?",
        "Wie groß wärst du, wenn du die Wahl hättest?",
        "Wie teuer war das teuerste Objekt, dass du jemals kaputt gemacht hast?",
        "Wie viele Stunden schläfst du idealerweise nachts?",
        "Wie viele Sportarten hast du schon mindestens ein Jahr lang betrieben?",
        "Wie viele Vornamen hast du (also auch zweite, dritte ...)?",
        "Wann wachst du durchschnittlich am Wochenende auf?",
        "Wie viele Flaschen mit hochprozentigen Spirituosen besitzt du zurzeit?",
        "Wie viele Minuten nach dem ersten Klingeln des Weckers stehst du durchschnittlich endgültig auf?",
        "Wie alt fühlst du dich innerlich?",
        "Wie viele Gläser alkoholischer Getränke trinkst du durchschnittlich pro Woche?",
        "Wie oft hast du den Film \"Titanic\" gesehen?",
        "Wie lange ist dein perfektes Nickerchen?",
        "Wenn es keinerlei Einschränkungen gäbe, wie viele Haustiere hättest du dann gerne?",
        "Wie oft hast du in deinem Leben schon Reifen gewechselt?",
        "Wie viele verschiedene Parfüms besitzt du?",
        "Wie viele der Personen hier am Tisch würdest du beim Armdrücken besiegen?",
        "Wie viel wärst du maximal bereit, in einem Restaurant der Extraklasse zu bezahlen?",
        "Wie viele Jahre deines Lebens würdest du hergeben, um dich ab sofort beliebig auf teleportieren zu können?",
        "Wie lange dauert oder dauert deine längste Freundschaft?",
        "Wie viele Stunden verbringst du bei einem Tagesausflug an die Küste idealerweise direkt am Strand?",
        "In wie vielen Sprachen kennst du Schimpfwörter?",
        "Wie viele Tattoos hast du?",
        "Welche Schuhgröße hast du?", "Was denkst du, wie alt du wirst?",
        "Bei durchschnittlich wie vielen Mahlzeiten pro Woche isst du Fleisch?",
        "Wie viele Apps hast du auf deinem Smartphone installiert?",
        "Wie viele Paar Schuhe besitzt du?",
        "Wie viele deiner bisherigen romantischen Beziehungen haben länger als ein Jahr gedauert?",
        "Wie viele Schlüssel hast du an deinem Schlüsselring?",
        "Um wie viel Uhr gehst du normalerweise unter der Woche ins Bett?",
        "Wie viel würdest du höchstens für ein Konzert deiner Lieblingsband bei dir zu Hause bezahlen?",
        "Wie lange brauchst du, um zur Arbeit oder Schule zu gehen?",
        "Wie viele Jahre deines Lebens würdest du hergeben, um jetzt sofort zum Milliardär zu werden?",
        "Wie viele Quadratmeter hätte dein ideales Zuhause (ohne Garten)?",
        "Wie viele Jahre deines Lebens würdest du hergeben, um alle Sprachen der Welt perfekt zu sprechen?",
        "Wie viele Hüte, Kappen, Mützen etc. besitzt du?",
        "Für wie viele Sekunden könntest du den Atem anhalten?",
        "Wann wachst du normalerweise unter der Woche morgens auf?",
        "Wie viele der Personen hier am Tisch könntest du bei Scrabble besiegen?",
        "Wie oft im Jahr würdest du Disneyland Paris besuchen, wenn Reise und Eintritt umsonst wären?",
        "Wie viele Bücher liest du durchschnittlich in einem Jahr?",
        "Du hast eine Reise zum Mond gewonnen. Wie lange soll sie dauern?",
        "Welches Jahr in der Weltgeschichte findest du am faszinierendsten?",
        "In wie vielen Sprachen kannst du \"Ich liebe dich\" sagen?",
        "Wie viele Liegestütze hintereinander könntest du schaffen?",
        "Wie viele der Personen hier am Tisch würdest du im 100-Meter-Lauf besiegen?",
        "Wie viele Nächte nacheinander hast du bisher maximal in einem Zelt übernachtet?",
        "Welches Jahr würdest du wählen, wenn du in der Zeit reisen und einen Tag in einem anderen Jahr verbringen könntest?",
        "Wie viele Cousins und Cousinen hast du?",
        "Wie viele Minuten wartest du maximal an einem Restaurant auf einem freien Tisch?",
        "Wie viel Bargeld hast du normalerweise bei dir?",
        "Wie viele Topfpflanzen stehen bei dir zu Hause?",
        "Wie viele Kontinente hast du schon betreten?",
        "Wie viele Sekunden hältst du aus, ohne zu zwinkern?",
        "Wie oft isst du durchschnittlich im Monat Fastfood?",
        "Wie oft gehst du durchschnittlich jeden Tag ins Bad?",
        "Wenn du bis zum Lebensende immer gleich alt sein müsstest und du das festlegen dürftest, wie alt wärst du dann gerne?",
        "Wie viele M&M's Schokolinsen könntest du auf einmal in deinen Mund bekommen?",
        "Wie viele Minuten brauchst du durchschnittlich morgens für dein äußeres Erscheinungsbild?",
        "Wie viele Minuten vorher erscheinst du normalerweise vor Ort zu einem wichtigen Termin?",
        "Wie lange übst du schon dein liebstes Hobby aus?",
        "Wie lange dauerte oder dauert deine längste romantische Beziehung?",
        "Wie lange würde deine ideale Mittelmeerkreuzfahrt dauern?",
        "Wie oft im Jahr gehst du normalerweise zum Friseur?",
        "Wie oft warst du schon Skifahren oder Snowboarden?",
        "Wie viele Jahre deines Lebens würdest du hergeben, um ein Musikinstrument deiner Wahl sofort perfekt spielen zu können?",
        "Wie viele Sammlungen irgendwelcher Gegenstände hast du?",
        "Wie viele Tage dauerte deine längste Reise bisher?",
        "Welches Jahrzehnt des 20. Jahrhunderts ist dir musikalisch gesehen das liebste?",
        "Von allen Einschränkungen, wie viele Kinder würdest du am liebsten irgendwann einmal haben?",
        "Was wäre die ideale Anzahl von Urlaubstagen im Jahr für dich?",
        "Stell dir vor, du gewinnst ein All-Inclusive-Urlaub auf einer privaten Insel. Wie lange würdest du dort bleiben wollen?",
        "Wie viele Filme siehst du durchschnittlich im Monat?",
        "Wie oft gehst du normalerweise im Monat essen? In ein Restaurant, also kein Fastfood oder Lieferservice?",
        "Wie lang könntest du die Balance halten, wenn du nur auf einem Bein stehst?",
        "In welchem Alter bist du in eine eigene Wohnung gezogen?",
        "Wie oft gehst du durchschnittlich in der Woche Lebensmittel einkaufen?",
        "Wie oft trainierst du durchschnittlich im Monat?",
        "Wie alt warst du in deiner frühesten Kindheitserinnerung?",
        "Wie oft bist du in deinem Leben schon umgezogen?",
        "Wie alt warst du, als du deinen ersten regelmäßigen Job angefangen hast?",
        "Wie oft kannst du fehlerfrei nacheinander \"Hans hackt Holz hinterm Haus\" sagen, ohne dich zu verhaspeln?",
        "Wie viele Tage mit Schnee im Jahr gäbe es, wenn es nach dir ginge?",
        "Wie viele Museen hast du in den letzten zwölf Monaten besucht?",
        "Wie lange lebst du schon in deinem jetzigen Zuhause?",
        "Wie viele Minuten duschst du durchschnittlich?",
        "Wie viele Tassen Kaffee und/oder Tee hast du heute schon getrunken?",
        "Wenn du in dieser Sekunde 50.000 Euro in bar bekommen würdest, wie lange bräuchtest du, um alles auszugeben?",
        "Wie viel würdest du maximal für einen einwöchigen Aufenthalt im Weltall ausgeben?",
        "Wie viele Gesellschaftsspiele besitzt du?",
        "Wie hoch müsste dein Jahresgehalt sein, wenn du ein Jahr lang auf einer Forschungsstation in der Antarktis arbeiten solltest?"
    )

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        supportActionBar?.hide()
        setContentView(R.layout.activity_spiel2)

        val btnSpiel21 = findViewById<Button>(R.id.btnSpiel21)
        val btnSpiel22 = findViewById<Button>(R.id.btnSpiel22)

        // Klick-Listener für btnSpiel1
        btnSpiel21.setOnClickListener {
            val randomIndex = Random.nextInt(von0bis100.size)
            btnSpiel21.text = von0bis100[randomIndex]
        }

        // Klick-Listener für btnSpiel2
        btnSpiel22.setOnClickListener {
            val randomIndex = Random.nextInt(freitextfragen.size)
            btnSpiel22.text = freitextfragen[randomIndex]
        }

    }
}
