name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # code-quality:
  #   name: Code Quality & Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: temurin
  #         java-version: 17

  #     - name: Grant execute permission to gradlew
  #       run: chmod +x ./gradlew

  #     - name: Run Lint
  #       run: ./gradlew lint

  #     - name: Run detekt
  #       run: ./gradlew detekt

  #     - name: Run Unit Tests
  #       run: ./gradlew testDebugUnitTest


    # needs: code-quality WICHTIG HINTER NAME EINFÜGEN 

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

  instrumentation-tests:
    name: Instrumentation Tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        api-level: [33]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: ./artifacts/debug-apk

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run instrumentation tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          emulator-options: "-no-window -no-audio -no-snapshot-save -no-boot-anim -accel auto"
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

      - name: Wait for emulator to boot
        run: |
          adb wait-for-device
          boot_completed=""
          until [[ "$boot_completed" == "1" ]]; do
            boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
            echo "Waiting for emulator to boot... ($boot_completed)"
            sleep 5
          done
