name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build & Test on API ${{ matrix.api-level }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        api-level: [29, 34, 35]

    env:
      ANDROID_SDK_ROOT: /usr/local/android-sdk
      JAVA_HOME: /usr/lib/jvm/adoptopenjdk-17-hotspot

    steps:
      # 1) Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Java 17 installieren
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3) Gradle-Cache
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4) SDK-Tools (cmdline-tools) sicherstellen
      #    auf Ubuntu-Runnern sind oft nur 'tools' installiert,
      #    hier legen wir 'latest' an, falls noch nicht vorhanden.
      - name: Prepare cmdline-tools
        run: |
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
            mv $ANDROID_SDK_ROOT/tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          fi
        shell: bash

      # 5) SDK-Plattform + Emulator + Build-Tools installieren
      - name: Install SDK packages for API ${{ matrix.api-level }}
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platforms;android-${{ matrix.api-level }}" \
            "system-images;android-${{ matrix.api-level }};google_apis;x86_64" \
            "build-tools;35.0.0" \
            "platform-tools" \
            "emulator"
        shell: bash

      # 6) Lizenzen akzeptieren (doppelt hält besser)
      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        shell: bash

      # 7) Build & Unit-Tests
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      # 8) Instrumentation-Tests auf Emulator
      - name: Run instrumentation tests on API ${{ matrix.api-level }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -no-audio -no-snapshot
          script: ./gradlew connectedDebugAndroidTest

      # 9) APK als Artifact speichern (optional)
      - name: Upload debug APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apk-api-${{ matrix.api-level }}
          path: app/build/outputs/apk/debug/app-debug.apk
