name: Android CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  # code-quality:
  #   name: Code Quality & Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up JDK
  #       uses: actions/setup-java@v4
  #       with:
  #         distribution: temurin
  #         java-version: 17

  #     - name: Grant execute permission to gradlew
  #       run: chmod +x ./gradlew

  #     - name: Run Lint
  #       run: ./gradlew lint

  #     - name: Run detekt
  #       run: ./gradlew detekt

  #     - name: Run Unit Tests
  #       run: ./gradlew testDebugUnitTest


    # needs: code-quality WICHTIG HINTER NAME EINFÜGEN 

  instrumentation-tests:
    name: Instrumentation Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [33]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Start emulator and run instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          target: google_apis
          profile: Nexus 6
          emulator-options: "-no-window -no-audio"
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest

#  build-apk:
#    name: Build Debug APK
#    needs: [instrumentation-tests]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4

#      - name: Set up JDK
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17

#      - name: Grant execute permission to gradlew
#        run: chmod +x ./gradlew

#      - name: Build Debug APK
#        run: ./gradlew assembleDebug

#      - name: Upload APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: debug-apk
#          path: app/build/outputs/apk/debug/app-debug.apk
