name: Build Test.apk

on:
  workflow_call:

jobs:
  build:
    name: Build Impulse.apk
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/Setup Gradle

      - name: Build APK
        env:
          BRANCH_REF: ${{ github.ref }}
          PR_BASE_REF: ${{ github.event.pull_request.base.ref || '' }}
        run: |
          echo "GitHub ref: $BRANCH_REF"
          echo "PR base ref: $PR_BASE_REF"

          if [[ "$BRANCH_REF" == "refs/heads/main" || "$PR_BASE_REF" == "main" ]]; then
            echo "Building Release APK"
            ./gradlew --no-daemon assembleRelease
            mv app/build/outputs/apk/release/app-release.apk Impulse.apk
          else
            echo "Building Debug APK"
            ./gradlew --no-daemon assembleDebug
            mv app/build/outputs/apk/debug/app-debug.apk Impulse.apk
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Impulse.apk
          path: Impulse.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: app/build/reports
