name: Build Test.apk

on:
  workflow_call:

jobs:
  build:
    name: TEST-Impulse.apk
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/Setup Gradle

      - name: Build Debug APK
        run: ./gradlew --no-daemon assembleDebug

      - name: Rename APK
        run: mv app/build/outputs/apk/debug/app-debug.apk TEST-Impulse.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TEST-Impulse.apk
          path: TEST-Impulse.apk

      - name: Upload build logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: app/build/reports
