name: Build Test.apk

on:
  push:
    branches:
      - main
      - dev
      - feature/optimierung-ci-cd-build
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build TEST-Impulse.apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TEST-Impulse.apk
          path: app/build/outputs/apk/debug/app-debug.apk
