name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    name: Build & Test on All API Levels
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 34, 35]  # 👈 Hier testen wir 3 API-Levels
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install SDK packages
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=${ANDROID_SDK_ROOT} \
            "platforms;android-${{ matrix.api-level }}" \
            "system-images;android-${{ matrix.api-level }};google_apis;x86_64" \
            "build-tools;35.0.0" \
            "platform-tools" \
            "emulator"

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run instrumentation tests on API ${{ matrix.api-level }}
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -no-audio -no-snapshot
          script: ./gradlew connectedDebugAndroidTest
