name: Code Quality Check

on:
  push:
    branches:
      - main
      - dev
      - feature/**
  pull_request:
    branches:
      - main
      - dev
      - feature/**

jobs:
  code-quality-check:
    name: Code-Check durch ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [detekt, testDebugUnitTest, lint]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run ${{ matrix.task }}
        run: ./gradlew ${{ matrix.task }}


      - name: Upload Detekt Report
        if: matrix.task == 'detekt' && always()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/problems/problems-report.html