name: Code Quality Check

on:
  workflow_call:

jobs:
  code-quality-check:
    name: durch ${{ matrix.task }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ detekt, testDebugUnitTest, lint ]
      fail-fast: false

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/Setup Gradle

      # set +e: Dadurch wird der Code auch nach einem Fehler weiter ausgeführt.
      # errorCode: Speichert den letzten Error Code, damit er manuell in meine eigene Fehlermeldung übersetzt wird.
      - name: Run ${{ matrix.task }}
        run: |
          set +e
          case "${{ matrix.task }}" in
            lint)
              timeout 10s ./gradlew ${{ matrix.task }}
              ;;
            *)
              timeout 10s ./gradlew ${{ matrix.task }}
              ;;
          esac
          errorCode=$?
          RED='\033[0;31m'
          NC='\033[0m'
          [ $errorCode -eq 124 ] && echo -e "\n${RED}(~*-*)~ Eriks Fehlermeldung: Timeout dieses workflow-steps überschritten! ~(*-*~)${NC}"
          exit $errorCode
