name: Code Quality Check

on:
  workflow_call:

jobs:
  code-quality-check:
    name: durch ${{ matrix.task }}
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ detekt, testDebugUnitTest, lint ]
      fail-fast: false

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/Setup Gradle

      - name: Run ${{ matrix.task }} with timeout
        run: |
          case "${{ matrix.task }}" in
            lint)
              timeout 60s ./gradlew ${{ matrix.task }}
              ;;
            *)
              timeout 30s ./gradlew ${{ matrix.task }}
              ;;
          esac
