name: Code Quality Check

on:
  workflow_call:

jobs:
  code-quality-check:
    name: durch ${{ matrix.task }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [detekt, testDebugUnitTest, lint]
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/Setup Android Environment

      - name: Run ${{ matrix.task }}
        run: ./gradlew ${{ matrix.task }}
