name: dev Pipeline

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - 'app/src/main/java/de/seleri/tools/Daten/**'
      - 'tools/**'
      - 'README.md'
  pull_request:
    branches: [ dev ]
    paths-ignore:
      - 'app/src/main/java/de/seleri/tools/Daten/**'
      - 'tools/**'
      - 'README.md'

jobs:
  code-quality-check:
    name: Code-Check
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Code Quality Check.yml

  emulator-test:
    name: Emulator-Test (nur API 33)
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Emulator-Tests.yml
    with:
      api-filter: "33"

  build:
    name: Build
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Build.yml
