name: dev Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  code-quality-check:
    name: Code-Check
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Code Quality Check.yml

  build:
    name: Build
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Build.yml