name: Emulator-Tests

on:
  workflow_call:
    inputs:
      api-filter:
        required: false
        type: string
        default: "29,30,31,32,33,34"

jobs:
  emulator-tests:
    name: auf API
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        api-level: [29, 30, 31, 32, 33, 34]

    steps:
      - name: Checkout Code
        if: contains(inputs['api-filter'], format('{0}', matrix.api-level))
        uses: actions/checkout@v4

      - name: Enable KVM
        if: contains(inputs['api-filter'], format('{0}', matrix.api-level))
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Gradle
        if: contains(inputs['api-filter'], format('{0}', matrix.api-level))
        uses: ./.github/actions/Setup Gradle

      - name: AVD cache (API 30+) # Das Caching für API <= 29 gerät manchmal in eine Endlosschleife
        if: matrix.api-level > 29 && contains(inputs['api-filter'], format('{0}', matrix.api-level))
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: ~/.android/avd
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching (API 30+)
        if: steps.avd-cache.outputs.cache-hit != 'true' && matrix.api-level > 29 && contains(inputs['api-filter'], format('{0}', matrix.api-level))
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-boot-timeout: 600
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run tests (API <= 29)
        if: matrix.api-level < 30 && contains(inputs['api-filter'], format('{0}', matrix.api-level))
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-boot-timeout: 600
          api-level: ${{ matrix.api-level }}
          arch: x86 # benötigt für API <= 29
          force-avd-creation: ${{ matrix.api-level < 30}} # kein Caching
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck

      - name: run tests (API 30+)
        if: matrix.api-level > 29 && contains(inputs['api-filter'], format('{0}', matrix.api-level))
        uses: reactivecircus/android-emulator-runner@v2
        with:
          emulator-boot-timeout: 600
          api-level: ${{ matrix.api-level }}
          arch: x86_64 # benötigt für API 30+
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -snapshot default
          disable-animations: true
          script: ./gradlew connectedCheck
