name: Emulator-Tests

on:
  workflow_call:

jobs:
  emulator-tests:
    name: auf API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29, 34]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Android Environment
        uses: ./.github/actions/Setup Android Environment

      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: TEST-Impulse.apk
          path: ./artifacts/TEST-Impulse.apk

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Run Emulator-Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck
