name: Emulator-Tests

on:
  workflow_call:

jobs:
  emulator-tests:
    name: auf API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/Setup Android Environment

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: TEST-Impulse.apk
          path: ./artifacts/TEST-Impulse.apk

      - name: Run instrumentation tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          emulator-options: "-no-window -no-audio -no-boot-anim -accel auto -gpu swiftshader_indirect -memory 2048"
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
