name: Emulator-Tests

on:
  workflow_call:

jobs:
  emulator-tests:
    name: Emulator-Test auf API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle cache
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: false
          cache-cleanup: never # Das hier löschen, falls es mit dem Caching-Speicherplatz auf github eng wird.

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Download APK artifacts
        uses: actions/download-artifact@v4
        with:
          name: TEST-Impulse.apk
          path: ./artifacts/TEST-Impulse.apk

      - name: Run instrumentation tests on emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: default
          arch: x86_64
          emulator-options: "-no-window -no-audio -no-boot-anim -accel auto -gpu swiftshader_indirect -memory 2048"
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
