name: feature Pipeline

on:
  push:
    branches: [ feature/** ]
    paths-ignore:
      - 'app/src/main/java/de/seleri/tools/Daten/**'
      - 'tools/**'
      - 'README.md'
  pull_request:
    branches: [ feature/** ]
    paths-ignore:
      - 'app/src/main/java/de/seleri/tools/Daten/**'
      - 'tools/**'
      - 'README.md'

jobs:
  code-quality-check:
    name: Code-Check
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Code Quality Check.yml