name: feature Pipeline

on:
  push:
    branches: [feature/**]
  pull_request:
    branches: [feature/**]

jobs:
  code-quality-check:
    name: Code-Check
    uses: ./.github/workflows/Code Quality Check.yml