name: main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality-check:
    name: Code-Check
    uses: ./.github/workflows/Code Quality Check.yml

  build:
    name: Build
    uses: ./.github/workflows/Build.yml

  emulator-tests:
    name: Emulator-Tests
    uses: ./.github/workflows/Emulator-Tests.yml