name: main Pipeline

on:
  push:
    branches: [ main, feature/optimierung-ci-cd-emulator ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality-check:
    uses: ./.github/workflows/Code Quality Check.yml

  build:
    uses: ./.github/workflows/Build.yml

  emulator-tests:
    needs: [ code-quality-check, build ]
    uses: ./.github/workflows/Emulator-Tests.yml