name: main Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'app/src/main/java/de/seleri/tools/Daten/**'
      - 'tools/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'app/src/main/java/de/seleri/tools/Daten/**'
      - 'tools/**'

jobs:
  code-quality-check:
    name: Code-Check
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Code Quality Check.yml

  build:
    name: Build
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Build.yml

  emulator-tests:
    name: Emulator-Tests
    if: "!startsWith(github.event.head_commit.message, 'Merge')"
    uses: ./.github/workflows/Emulator-Tests.yml